### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by flip111** [clbustos/PHP_Beautifier#11]
This package is hard to find right now ... please add support for composer and packagist.org

**Comment by akalongman** [comment]
@flip111 Can you tell me how add it in composer?

**Comment by flip111** [comment]
@akalongman are you maintaining the package now? Anyway instructions are here: https://packagist.org/about

**Comment by flip111** [comment]
Closing because https://github.com/clbustos/PHP_Beautifier/pull/16 got merged.
